#
# private/config/app.dist.yaml
#

# defined any application-specific components here
components:

    # responsible for loading services and routes
    - Kispiox\Component\DefaultComponent

# the main run routine [class, method]
run: ['Kispiox\Component\DefaultComponent', 'run']

