#
# private/config/app.dist.yaml
#

# defined any application-specific components here
components:

    # safe to remove after installation
    - Kispiox\Component\DefaultComponent

# the main run routine [class, method]
run: [MattFerris\Bridge\Components\HttpRouting\HttpRoutingComponent, run]

