#
# private/config/app.dist.yaml
#

# defined any application-specific components here
components:

    # responsible for loading services and routes
    - Kispiox\Component\DefaultComponent

# the main run routine [class, method]
run: ['Kispiox\Component\DefaultComponent', 'run']

# log file
#logfile: 'private/logs/error.log'

# debug log file
#debugfile: 'private/logs/debug.log'

# authentication settings
auth:

    # the key to use to sign auth tokens, required
    # key: 'superSecretAndSecureKey'

    # how long authentication is valid for
    # duration: 3600
