#
# Kispiox - A lightweight application framework
# www.bueller.ca/kispiox
#
# private/config/kispiox.dist.yaml
# @copyright Copyright (c) 2016 Matt Ferris
# @author Matt Ferris <matt@bueller.ca>
#
# Licensed under BSD 2-clause license
# www.bueller.ca/kispiox/license
#
kispiox:

    # define loadable components
    components:

        # first pass components
        -
            - MattFerris\Bridge\Components\Events\EventsComponent

        # second pass components
        -
            - MattFerris\Application\Component

        # third pass components
        -
            - MattFerris\Bridge\Components\HttpRouting\HttpRoutingComponent


