language: php

php:
  - 5.6

before_script:
    - composer update

script:
    - mkdir -p build/logs
    - php vendor/phpunit/phpunit/phpunit
    
after_success:
  - travis_retry php vendor/bin/coveralls
